Add NodePath
RobSimulatorGroup/gobot pull request #25
Opened 2023-01-16 20:04 UTC by StephenYu-R

A pre-parsed relative or absolute path in a scene tree, for use with Node related functionalities. It can reference a node, a resource within a node, or a property of a node or resource.

Following methods are implemented.
- IsAbsolute
- GetNameCount
- GetName
- GetSubNameCount
- GetSubName
- GetNames
- GetSubNames
- operator String()
- IsEmpty
- operator==
- operator!=
- Simplify
- Simplified

The boolean "valid_" is held to check if a node_path is good to use.

**This PR is for API checks and is currently yet to be merged as unit-tests will be completed soon.**

2023-01-17 21:52 UTC, StephenYu-R commented on include/gobot/log.hpp
> +#define LOG_OFF gobot::Logger::getInstance().getLogger()->set_level(spdlog::level::off)
Macros here are for temporarily turning off log messages for running tests. Please correct me if a better approach is recommended. @Wuqiqi123

2023-01-17 21:56 UTC, StephenYu-R commented on include/gobot/scene/node_path.hpp
> +    struct Data {
Wrapped data to allow further changes to private members.

2023-01-17 21:57 UTC, StephenYu-R commented on src/gobot/scene/node_path.cpp
> +        LOG_ERROR("Invalid index {}.", idx);
Yet to be implemented in error_macros.

2023-01-18 09:36 UTC, StephenYu-R commented
Completed doc-string to clarify API usage.

2023-01-20 14:11 UTC, Wuqiqi123 requested changes

2023-01-20 14:11 UTC, Wuqiqi123 commented on include/gobot/log.hpp
> +#include "gobot/core/types.hpp"
why include types

2023-01-20 14:11 UTC, Wuqiqi123 commented on src/gobot/scene/node_path.cpp
> +static constexpr Qt::SplitBehaviorFlags FlagSkipEmptyParts = Qt::SkipEmptyParts;
how about move FlagSkipEmptyParts into NodePath.
And currently I name static value as  s_xxx

2023-01-20 14:11 UTC, Wuqiqi123 commented on include/gobot/scene/node_path.hpp
> +    bool valid_ = false;
Do we need variable valid_ ?

2023-01-20 14:11 UTC, Wuqiqi123 commented on src/gobot/scene/node_path.cpp
> +NodePath::NodePath(const String &path) {
if path is invalid, path_list and subpath_list are all empty

2023-01-20 14:11 UTC, Wuqiqi123 commented on include/gobot/core/marcos.hpp
> +#if defined(__GNUC__)
20 不是有这个吗 [[unlikely]]

2023-01-20 14:11 UTC, Wuqiqi123 commented on src/gobot/scene/node_path.cpp
> +    return np;
Add 
""GOBOT_REGISTRATION{}" for the NodePath type registration

2023-01-20 14:11 UTC, Wuqiqi123 commented on tests/scene/test_node_path.cpp
> +class TestNodePath : public gobot::NodePath {
Do we need TestNodePath

2023-01-20 14:11 UTC, Wuqiqi123 commented on include/gobot/scene/node_path.hpp
> +    struct Data {
struct 里面的 变量就不加后缀 “_”

2023-01-20 14:11 UTC, Wuqiqi123 commented on src/gobot/scene/node_path.cpp
> +    data_.path_ = std::vector<String>(path_list.begin(), path_list.end());
Can we use std::move or swap here

2023-01-20 14:11 UTC, Wuqiqi123 commented on src/gobot/scene/node_path.cpp
> +bool NodePath::operator==(const NodePath &path) const {
Can we use https://en.cppreference.com/w/cpp/language/default_comparisons

> A class can define operator== as defaulted, with a return value of bool. This will generate an equality comparison of each base class and member subobject, in their declaration order. Two objects are equal if the values of their base classes and members are equal. The test will short-circuit if an inequality is found in members or base classes earlier in declaration order.
> 
> Per the rules for operator==, this will also allow inequality testing:

2023-01-20 14:20 UTC, StephenYu-R commented on include/gobot/core/marcos.hpp
> +#if defined(__GNUC__)
Removed for duplicate.

2023-01-21 03:44 UTC, Wuqiqi123 commented on src/gobot/scene/node_path.cpp
> +bool NodePath::operator==(const NodePath &path) const {
这个你看了没

2023-01-21 04:16 UTC, StephenYu-R commented on include/gobot/core/marcos.hpp
> +#if defined(__GNUC__)
Removed for duplicate.

2023-01-21 04:16 UTC, StephenYu-R commented on include/gobot/log.hpp
> +#include "gobot/core/types.hpp"
Because following codes require a gobot::String type.

template<>
struct fmt::formatter<gobot::String> : fmt::formatter<std::string>

2023-01-21 04:16 UTC, StephenYu-R commented on include/gobot/scene/node_path.hpp
> +    struct Data {
Removed "_".

2023-01-21 04:16 UTC, StephenYu-R commented on src/gobot/scene/node_path.cpp
> +static constexpr Qt::SplitBehaviorFlags FlagSkipEmptyParts = Qt::SkipEmptyParts;
Put it into class declaration with name S_FLAG_SKIP_EMPTY_PARTS

2023-01-21 04:16 UTC, StephenYu-R commented on src/gobot/scene/node_path.cpp
> +NodePath::NodePath(const String &path) {
Class members data_.path and data_.subpath are initialized to be an empty string, so do nothing and return.

2023-01-21 04:16 UTC, StephenYu-R commented on src/gobot/scene/node_path.cpp
> +    data_.path_ = std::vector<String>(path_list.begin(), path_list.end());
Sure, good catch.

2023-01-21 04:16 UTC, StephenYu-R commented on src/gobot/scene/node_path.cpp
> +bool NodePath::operator==(const NodePath &path) const {
Our compiler CMake 3.16 implicitly delete the default 'operator=='.

2023-01-21 04:16 UTC, StephenYu-R commented on src/gobot/scene/node_path.cpp
> +    return np;
Added registration.

Not sure if construct raw pointer?

2023-01-21 04:16 UTC, StephenYu-R commented on tests/scene/test_node_path.cpp
> +class TestNodePath : public gobot::NodePath {
Removed class definition for TestNodePath.

2023-01-21 04:16 UTC, StephenYu-R commented on src/gobot/scene/node_path.cpp
> +    return np;
Registered as object

2023-01-21 04:17 UTC, StephenYu-R commented on src/gobot/scene/node_path.cpp
> +bool NodePath::operator==(const NodePath &path) const {
Replaced with default operator==

2023-01-21 04:18 UTC, StephenYu-R commented on include/gobot/scene/node_path.hpp
> +    bool valid_ = false;
Outdated, mark as resolved.

2023-01-21 05:06 UTC, Wuqiqi123 commented on src/gobot/scene/node_path.cpp
> +    data_.path = std::move(std::vector<String>(path_list.begin(), path_list.end()));
我原来的意思是这边为什么要重新构造一个std::vector<String>, 
为什么不能这样data_.path = std::move(path_list) 或者 data.path.swap(path_list), 这样就不需用重新构造一个新的vector

2023-01-21 05:08 UTC, StephenYu-R commented on src/gobot/scene/node_path.cpp
> +    data_.path = std::move(std::vector<String>(path_list.begin(), path_list.end()));
本来用 toStdVector，然后 deprecated，就直接构造了

2023-01-21 06:38 UTC, Wuqiqi123 commented on src/gobot/scene/node_path.cpp
> +            .constructor<const NodePath&>()(CtorAsObject)
只留无参数的构造函数， 其他的构造函数虽然可以注册， 但是没人会使用

2023-01-21 11:28 UTC, StephenYu-R commented
renamed GetStrData()

2023-01-21 11:30 UTC, StephenYu-R commented
Resolved all issues, please squash and merge.

2023-01-21 11:45 UTC, Wuqiqi123 approved these changes

2023-01-21 11:45 UTC, merged