1 serialization and deserialization object using json
RobSimulatorGroup/gobot pull request #31
Opened 2023-01-27 11:55 UTC by Wuqiqi123

1. Remove 3rdparty intrusive_ptr and using boost::intrusive_ptr
2. Save resource and load resource

```
{
    "__EXT_RESOURCES__": [],
    "__META_TYPE__": "RESOURCE",
    "__RESOURCE__": {
        "material": "SubResource(Material3D_1QPI7)",
        "resource_name": "",
        "resource_path": "res://box_mesh.jres",
        "width": 1.100000023841858
    },
    "__SUB_RESOURCES__": [
        {
            "__ID__": "Material3D_1QPI7",
            "__TYPE__": "Material3D",
            "albedo": {
                "alpha": 1.0,
                "blue": 0.0,
                "green": 0.0,
                "red": 0.0
            },
            "resource_name": "",
            "resource_path": ""
        }
    ],
    "__TYPE__": "BoxMesh",
    "__VERSION__": 1
}
```

TODO
1. add RefWeak
2. PackageScene

2023-01-30 08:45 UTC, StephenYu-R requested changes
Please correct me if I misunderstood.

2023-01-30 08:45 UTC, StephenYu-R commented on src/gobot/core/config/project_setting.cpp
> +#include "gobot/log.hpp"
Unused "#include "gobot/log.hpp""

2023-01-30 08:45 UTC, StephenYu-R commented on include/gobot/core/config/project_setting.hpp
> +    ProjectSettings();
The implementation is okay, while in case of Singleton pattern, the constructor should always be **private/protected** to prevent direct construction calls with "new" operator. And this class shouldn't be copyable or assignble, like

ProjectSettings (ProjectSettings &param) = deleted;
void operator=(const ProjectSettings &param) = deleted;

2023-01-30 08:45 UTC, StephenYu-R commented on include/gobot/core/config/project_setting.hpp
> +    static ProjectSettings* GetSingleton();
GetInstance is clear.

2023-01-30 08:45 UTC, StephenYu-R commented on src/gobot/core/config/project_setting.cpp
> +String ProjectSettings::LocalizePath(const String &path) const {
This is implemented in NodePath::Simplify.

2023-01-30 08:45 UTC, StephenYu-R commented on include/gobot/core/io/resource.hpp
> +    // If take_over is false and same path resource cache already existed, this operation will failed.
failed -> fail.

2023-01-30 08:45 UTC, StephenYu-R commented on include/gobot/core/io/resource.hpp
> +    // 5 char of number/uppercase letter/lowercase letter；
Please clarify this definition.

2023-01-30 08:45 UTC, StephenYu-R commented on include/gobot/core/io/resource.hpp
> +    String GetUniqueId() const;
variable -> various

2023-01-30 08:45 UTC, StephenYu-R commented on include/gobot/core/io/resource.hpp
>      virtual void SetPath(const String &path, bool take_over = false);
The default argument take_over will NOT be valid for an overridden virtual method.

2023-01-30 08:45 UTC, StephenYu-R commented on src/gobot/core/io/resource.cpp
>              ResourceCache::s_lock.unlock();
Better use unique_lock in a scope instead of lock/unlock.

Not sure why recursive_mutex is in need.

2023-01-30 08:45 UTC, StephenYu-R commented on src/gobot/core/io/resource.cpp
> +        }
re = re->CloneForLocalScene(for_scene);

2023-01-30 08:45 UTC, StephenYu-R commented on src/gobot/core/io/resource.cpp
> +        PropertyInfo property_info;
Need a macro to wrap raw LOG_ERRORs

2023-01-30 08:45 UTC, StephenYu-R commented on src/gobot/core/io/resource.cpp
> +void Resource::SetPathNotTakeOver(const String &path) {
~Resource() {
std::unique_lock(mutex);
erase...
}

2023-01-30 08:45 UTC, StephenYu-R commented on src/gobot/core/io/resource.cpp
> +    if (!resource.IsValid()) {
Need a macro for message log.

2023-01-30 08:45 UTC, StephenYu-R commented on src/gobot/core/io/resource.cpp
>      s_lock.lock();
put this critical section in a scope with unique_lock for RAII.

2023-01-30 10:00 UTC, StephenYu-R requested changes

2023-01-30 10:00 UTC, StephenYu-R commented on include/gobot/core/io/resource_loader.hpp
> +    virtual Ref<Resource> Load(const String &local_path,
Default arguments may not be passed to overridden methods.

2023-01-30 10:00 UTC, StephenYu-R commented on src/gobot/core/io/resource_loader.cpp
> +    bool found = false;
Unnecessary flag. 

Sanity checks ...

for () {
  if () return ...;
}

return ...;

2023-01-30 10:00 UTC, StephenYu-R commented on src/gobot/core/io/resource_loader.cpp
> +void ResourceLoader::AddResourceFormatLoader(Ref<ResourceFormatLoader> format_loader, bool at_front) {
Make format_loader as a const reference.

2023-01-30 10:00 UTC, StephenYu-R commented on src/gobot/core/io/resource_format_scene.cpp
> +#include "gobot/scene/resources/packed_scene.hpp"
unused

2023-01-30 10:00 UTC, StephenYu-R commented on src/gobot/core/io/resource_format_scene.cpp
> +ResourceFormatLoaderSceneInstance::ResourceFormatLoaderSceneInstance() {
cache_mode_ is not initialized.

2023-01-30 10:00 UTC, StephenYu-R commented on src/gobot/core/io/resource_format_scene.cpp
> +        is_scene_ = meta_type == "SCENE" ? true : false;
is_scene_ = meta_type == "SCENE";

2023-01-31 05:00 UTC, StephenYu-R commented
序列化没有做单元测试

2023-01-31 12:38 UTC, Wuqiqi123 commented on include/gobot/core/config/project_setting.hpp
> +    ProjectSettings();
This is the godot way of Singleton pattern. 
godot using T* as instance rather than T&(traditional Singleton pattern).
Because godot need register the class, so make constructor private can not do the registration.

2023-02-09 03:44 UTC, StephenYu-R approved these changes
LGTM, approved.

2023-02-09 03:47 UTC, merged