64 imgui initialize
RobSimulatorGroup/gobot pull request #71
Opened 2023-03-25 07:58 UTC by Wuqiqi123

1. refactor render pipeline(The scene render target changes to texture rather than window handle)
2. Initialize Imgui and guizmo

https://user-images.githubusercontent.com/37368540/227705007-b1f28920-168d-49f2-bf90-eb7cf1fede46.mp4

2023-03-26 15:37 UTC, StephenYu-R requested changes

2023-03-26 15:37 UTC, StephenYu-R commented on include/gobot/core/hash_combine.hpp
> +inline void HashCombine(std::size_t& seed, const T& v, Rest... rest)
Could you please explain this with a brief description?

2023-03-26 15:37 UTC, StephenYu-R commented on include/gobot/core/math/math_defs.hpp
> +inline bool FloatEquals(real_t a, real_t b) {
Please be careful at the "AlmostEquals" between two floating values, because the context may vary among different scenarios. For example, the absolute epsilon is not the same precision for length and degree. Also. the epsilon may be okay to a float number, but useless to a double due to precision loss.

In that case, you could do it with the followings,
1. Use std::numeric_limits with ulp, https://en.cppreference.com/w/cpp/types/numeric_limits/epsilon
2. return fabs(a - b) <= ( (fabs(a) < fabs(b) ? fabs(b) : fabs(a)) * epsilon), with arguments a, b and epsilon. While, fabs could be pretty slow.

2023-03-26 15:37 UTC, StephenYu-R commented on include/gobot/scene/camera3d.hpp
> +    Camera3D();
Could you please rename the file name as camera_3d.hpp by the naming convention.

2023-03-26 15:37 UTC, StephenYu-R commented on include/gobot/rendering/render_rid.hpp
> +class RenderRID {
We've implemented an RID allocator, could you please explain why we need a RenderRID?

2023-03-27 02:23 UTC, Wuqiqi123 commented on include/gobot/core/hash_combine.hpp
> +inline void HashCombine(std::size_t& seed, const T& v, Rest... rest)
HashCombine means combine two hash into a new hash value(How to hash a struct with different fields)
https://stackoverflow.com/questions/2590677/how-do-i-combine-hash-values-in-c0x

2023-03-27 02:51 UTC, Wuqiqi123 commented on include/gobot/rendering/render_rid.hpp
> +class RenderRID {
The bgfx has its own id system which called Handle(TextureHandle for example).  Besides,  bgfx using uint16_t as render id and the maximum of uint16_t as invalid value. The user can't decide how to allocate the Handle.
Combine gobot's RID and bgfx's Handle is difficult, but I imitate the key idea of gobot's RID of wrapping bgfx's Handle to RenderRID

2023-03-27 11:55 UTC, StephenYu-R approved these changes
LGTM, approved.

2023-03-27 11:57 UTC, merged